Verify Intallation(EXPERIMENT 1)

In [1]:
pip install tensorflow

Create Tensors(EXPERIMENT 2)


In [2]:
import tensorflow as tf
print(tf.__version__)


2.19.0


In [3]:
# 0 dimension tensor(Scalar value)
a =tf.constant(5)
print(a)

tf.Tensor(5, shape=(), dtype=int32)


In [4]:
#1 dimentor tensor called vector
v= tf.constant([1,2,3,4])
print(v)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [6]:
# to create a matrix using tensor and how to supply the argument(row by row)
m = tf.constant([[1,2],[3,4]])
print(m)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [8]:
t3 = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(t3)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


OPERATION IN TENSOR (EXPERIMENT- 3)

In [11]:
# operation in scalar
v= tf.constant(10)
u= tf.constant(10)
print(v+u)
print(v-u)
print(v*u)
print(v/u)
print(v^u)



tf.Tensor(20, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(100, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(0, shape=(), dtype=int32)


In [10]:
# operation in vector
a=tf.constant([10,20,30])
b = tf.constant([50,60,70])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a^b)

tf.Tensor([ 60  80 100], shape=(3,), dtype=int32)
tf.Tensor([-40 -40 -40], shape=(3,), dtype=int32)
tf.Tensor([ 500 1200 2100], shape=(3,), dtype=int32)
tf.Tensor([0.2        0.33333333 0.42857143], shape=(3,), dtype=float64)
tf.Tensor([56 40 88], shape=(3,), dtype=int32)


In [12]:
#operation on 2d
m = tf.constant([[1,2],[3,4]])
n = tf.constant([[5,6],[7,8]])
print(m+n)
print(m-n)
print(m*n)
print(m/n)
print(m^n)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[ 4  4]
 [ 4 12]], shape=(2, 2), dtype=int32)


Datatype and shape of tensor(EXPERIMENT_4)

In [ ]:
import tensorflow as tf

# Scalar (0D Tensor)
scalar = tf.constant(5)

# Vector (1D Tensor)
vector = tf.constant([10, 20, 30])

# Matrix (2D Tensor)
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])

# Scalar details
print("Scalar Tensor:", scalar)
print("Data type:", scalar.dtype)
print("Shape:", scalar.shape)
print("Number of dimensions:", scalar.ndim)
print()

# Vector details
print("Vector Tensor:", vector)
print("Data type:", vector.dtype)
print("Shape:", vector.shape)
print("Number of dimensions:", vector.ndim)
print()

# Matrix details
print("Matrix Tensor:", matrix)
print("Data type:", matrix.dtype)
print("Shape:", matrix.shape)
print("Number of dimensions:", matrix.ndim)


NUumpy array to Tenser(EXPERIMENT-5)

In [ ]:
import numpy as np

numpy_scalar = np.array(5)
tensor_scalar = tf.convert_to_tensor(numpy_scalar)

print("----- SCALAR -----")
print("\nNumPy Scalar:", numpy_scalar)
print("\nTensor Scalar:", tensor_scalar)



numpy_vector = np.array([1, 2, 3, 4])
tensor_vector = tf.convert_to_tensor(numpy_vector)


print("\nNumPy Vector:", numpy_vector)
print("\nTensor Vector:", tensor_vector)



numpy_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])
tensor_matrix = tf.convert_to_tensor(numpy_matrix)


print("\nNumPy Matrix:")
print(numpy_matrix)
print("\nTensor Matrix:")
print(tensor_matrix)