In [28]:
# import libraries
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.19.0


In [29]:
# enter corpus and some detail about them
corpus = [
    "deep learning models can solve complex problems",
    "machine learning is transforming the world",
    "artificial intelligence is the future of technology",
    "data science helps in making better decisions",
    "neural networks are inspired by the human brain",
    "python is widely used for machine learning",
    "big data requires efficient processing techniques",
    "supervised learning uses labeled data",
    "unsupervised learning finds hidden patterns",
    "reinforcement learning learns through rewards",

    "natural language processing enables computers to understand text",
    "computer vision allows machines to interpret images",
    "algorithms improve with more training data",
    "training a model requires clean and relevant data",
    "overfitting happens when a model memorizes training data",
    "regularization techniques help reduce overfitting",
    "gradient descent is used to minimize loss",
    "loss functions measure prediction errors",
    "deep learning models need large datasets",
    "feature engineering improves model performance",

    "data preprocessing is an important step in machine learning",
    "models should be evaluated using test data",
    "accuracy is not always the best evaluation metric",
    "precision and recall are useful for classification problems",
    "f1 score balances precision and recall",
    "cross validation improves model reliability",
    "hyperparameter tuning improves model performance",
    "neural networks consist of multiple layers",
    "activation functions introduce non linearity",
    "relu is a commonly used activation function",

    "sigmoid function outputs values between zero and one",
    "softmax function is used for multi class classification",
    "embedding layers convert words into dense vectors",
    "lstm networks are useful for sequence prediction",
    "rnn models can handle sequential data",
    "transformers are more powerful than rnn models",
    "attention mechanism improves model performance",
    "bert is a popular transformer based model",
    "gpt models are used for text generation",
    "language models learn patterns from text data",

    "ai is used in healthcare for diagnosis",
    "ai is used in finance for fraud detection",
    "ai is used in education for personalized learning",
    "self driving cars use computer vision",
    "chatbots use natural language processing",
    "recommendation systems suggest relevant content",
    "voice assistants understand spoken language",
    "data visualization helps in understanding trends",
    "cloud computing supports scalable machine learning",
    "edge computing enables real time predictions"
]

print("Number of sentences:", len(corpus))
print("\nSample corpus:")
for line in corpus:
    print("-", line)


Number of sentences: 50

Sample corpus:
- deep learning models can solve complex problems
- machine learning is transforming the world
- artificial intelligence is the future of technology
- data science helps in making better decisions
- neural networks are inspired by the human brain
- python is widely used for machine learning
- big data requires efficient processing techniques
- supervised learning uses labeled data
- unsupervised learning finds hidden patterns
- reinforcement learning learns through rewards
- natural language processing enables computers to understand text
- computer vision allows machines to interpret images
- algorithms improve with more training data
- training a model requires clean and relevant data
- overfitting happens when a model memorizes training data
- regularization techniques help reduce overfitting
- gradient descent is used to minimize loss
- loss functions measure prediction errors
- deep learning models need large datasets
- feature engineering i

In [30]:
# step 2 tokenizers: convert words → numbers

tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
word_index = tokenizer.word_index
total_words = len(tokenizer.word_index) + 1
print(total_words)
print("\nWord index:")
print(word_index)

198

Word index:
{'is': 1, 'data': 2, 'learning': 3, 'used': 4, 'for': 5, 'models': 6, 'model': 7, 'in': 8, 'are': 9, 'machine': 10, 'the': 11, 'language': 12, 'a': 13, 'and': 14, 'improves': 15, 'networks': 16, 'processing': 17, 'to': 18, 'text': 19, 'training': 20, 'performance': 21, 'function': 22, 'ai': 23, 'deep': 24, 'can': 25, 'problems': 26, 'of': 27, 'helps': 28, 'neural': 29, 'requires': 30, 'techniques': 31, 'patterns': 32, 'natural': 33, 'enables': 34, 'understand': 35, 'computer': 36, 'vision': 37, 'more': 38, 'relevant': 39, 'overfitting': 40, 'loss': 41, 'functions': 42, 'prediction': 43, 'precision': 44, 'recall': 45, 'useful': 46, 'classification': 47, 'layers': 48, 'activation': 49, 'rnn': 50, 'use': 51, 'computing': 52, 'solve': 53, 'complex': 54, 'transforming': 55, 'world': 56, 'artificial': 57, 'intelligence': 58, 'future': 59, 'technology': 60, 'science': 61, 'making': 62, 'better': 63, 'decisions': 64, 'inspired': 65, 'by': 66, 'human': 67, 'brain': 68, 'python'

In [31]:
# convert sentences into sequences
input_sequences = []

for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        n_gram = token_list[:i+1]
        input_sequences.append(n_gram)
print("Total training sequences:", len(input_sequences))
print("\nSome sequences before padding:")
for seq in input_sequences[:10]:
    print(seq)


Total training sequences: 275

Some sequences before padding:
[24, 3]
[24, 3, 6]
[24, 3, 6, 25]
[24, 3, 6, 25, 53]
[24, 3, 6, 25, 53, 54]
[24, 3, 6, 25, 53, 54, 26]
[10, 3]
[10, 3, 1]
[10, 3, 1, 55]
[10, 3, 1, 55, 11]


In [32]:
# step 4: padding-> make equal length because neural networks need fixed-size input

max_seq_len = max(len(x) for x in input_sequences)

input_sequences = pad_sequences(input_sequences, maxlen=max_seq_len, padding='pre')
print("Maximum sequence length:", max_seq_len)
print("\nPadded sequences:")
print(input_sequences[:10])


Maximum sequence length: 9

Padded sequences:
[[ 0  0  0  0  0  0  0 24  3]
 [ 0  0  0  0  0  0 24  3  6]
 [ 0  0  0  0  0 24  3  6 25]
 [ 0  0  0  0 24  3  6 25 53]
 [ 0  0  0 24  3  6 25 53 54]
 [ 0  0 24  3  6 25 53 54 26]
 [ 0  0  0  0  0  0  0 10  3]
 [ 0  0  0  0  0  0 10  3  1]
 [ 0  0  0  0  0 10  3  1 55]
 [ 0  0  0  0 10  3  1 55 11]]


In [33]:
# STEP 5: Split into X and y
X = input_sequences[:, :-1]
y = input_sequences[:, -1]
# STEP 6: One-hot encoding of output because Output is a word → we convert to probability distribution
y = tf.keras.utils.to_categorical(y, num_classes=total_words)

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)


Shape of X: (275, 8)
Shape of y: (275, 198)


In [40]:
# STEP 7: Build LSTM Model
from tensorflow.keras.layers import Dropout
model = Sequential()

model.add(Embedding(total_words, 50, input_length=max_seq_len-1))
model.add(LSTM(80))   # ↓ reduced from 150/100
model.add(Dropout(0.3))
model.add(Dense(total_words, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [41]:
# STEP 8: Train model
history = model.fit(X, y, epochs=100, verbose=1)




Epoch 1/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.0291 - loss: 5.2856    
Epoch 2/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0473 - loss: 5.2652 
Epoch 3/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0436 - loss: 5.2060 
Epoch 4/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0473 - loss: 5.0480 
Epoch 5/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0436 - loss: 4.9723 
Epoch 6/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0400 - loss: 4.8840 
Epoch 7/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0400 - loss: 4.8507 
Epoch 8/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0545 - loss: 4.8204 
Epoch 9/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0618 - loss: 4.8397 
Epoch 10/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0618 - loss: 4.8278 
Epoch 11/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0545 - loss: 4.7864 
Epoch 12/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0545 - 

In [42]:
# STEP 10: Prediction function
def predict_next_word(seed_text, next_words):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_seq_len-1, padding='pre')

        predicted = np.argmax(model.predict(token_list), axis=-1)

        for word, index in tokenizer.word_index.items():
            if index == predicted:
                seed_text += " " + word
                break

    return seed_text


In [43]:
print(predict_next_word("machine learning is", 3))
print(predict_next_word("deep learning", 3))
print(predict_next_word("data science", 3))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
machine learning is used in for
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
deep learning models can solve
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
data science helps in making
